//DEFINE CONSTANT
const RED_LINE_POSITION = 500;
const ARROW_CHANGE_SCORE = 10;
const PROBABILITY_BOOM = 20;
const PROBABILITY_STAR = 10;
const BUBBLE_SIZE = 60;
const TIME_DURATION_START = 10000;
const MINUMIM_TIME_DURATION = 2000;
const TIME_INTERVAL_START = 1500;
const MINUMIM_TIME_INTERVAL = 500;
const TIME_LEVEL_INTERVAL_MINUS = 300;
const TIME_LEVEL_DURATION_MINUS = 3000;
const SCORE_CHANGE_LEVEL_1 = 50;
const SCORE_CHANGE_LEVEL_2 = 100;
const SCORE_CHANGE_LEVEL_3 = 200;


